# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-02 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_auto_20190801_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unidad', models.CharField(max_length=40)),
                ('numero_linea', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GamaProductos',
            fields=[
                ('gama', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('descripcion_texto', models.CharField(max_length=30)),
                ('descripcion_html', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('forma_pago', models.CharField(max_length=30)),
                ('id_transaccion', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('fecha_pago', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('codigo_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('codigo_pedido', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('fecha_pedido', models.DateField()),
                ('fecha_esparada', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('estado', models.CharField(max_length=40)),
                ('comentarios', models.CharField(max_length=60)),
                ('codigo_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo_producto', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('gama', models.CharField(max_length=30)),
                ('dimensiones', models.CharField(max_length=30)),
                ('proveedor', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=50)),
                ('cantidad_stock', models.IntegerField()),
                ('precio_venta', models.CharField(max_length=30)),
                ('precio_proveedor', models.CharField(max_length=30)),
                ('gama_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.GamaProductos')),
            ],
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='codigo_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Pedidos'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='codigo_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Producto'),
        ),
    ]
