# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-05 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_producto_gama'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'permissions': set([('is_dos', 'Usuario Dos'), ('is_uno', 'Usuario Uno')])},
        ),
    ]
