# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-06 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20190805_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_producto',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
