# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-07 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20190806_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidos',
            options={},
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='codigo_pedido',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='fecha_entrega',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='fecha_esparada',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='fecha_pedido',
            field=models.CharField(max_length=10),
        ),
    ]
