# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-01 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo_cliente', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_cliente', models.CharField(max_length=30)),
                ('nombre_contacto', models.CharField(max_length=30)),
                ('apellido_contacto', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=30)),
                ('fax', models.IntegerField()),
                ('linea_direccion1', models.CharField(max_length=30)),
                ('linea_direccion2', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('pais', models.CharField(max_length=30)),
            ],
        ),
    ]
