# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-01 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cliente',
            name='limite_credito',
            field=models.CharField(default=True, max_length=30),
        ),
    ]
