# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-04 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_remove_empleado_cliente'),
        ('clientes', '0002_auto_20190801_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empleados.Empleado'),
        ),
    ]
