# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-04 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cliente',
            new_name='empleado',
        ),
    ]
