# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-01 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oficinas', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('codigo_empleado', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido1', models.CharField(max_length=30)),
                ('apellido2', models.CharField(max_length=30)),
                ('extencion', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('codigo_oficina', models.IntegerField()),
                ('codigo_jefe', models.IntegerField()),
                ('puesto', models.CharField(max_length=30)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
                ('oficina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oficinas.Oficinas')),
            ],
        ),
    ]
