# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-04 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='cliente',
        ),
    ]
